### ISSUE TITLE
Role Policy

### ISSUE THREAD

**Issue by kapsoft** [martinlindenberg/serverless-plugin-vpc#1]
Hi,

New to Serverless and trying your plugin in hope of getting vpc support working. Thanks in advance.

When you say add this to role policy:

"Effect": "Allow",
      "Action": [
        "ec2:CreateNetworkInterface",
        "ec2:DescribeNetworkInterfaces",
        "ec2:DeleteNetworkInterface"
      ],
      "Resource": "*"
      },

Where exactly is that? I put it under "customRole": {....

Deploy gives error: 

Serverless: Deploying functions in "dev" to the following regions: us-east-1  
Serverless: ------------------------  
Serverless: Failed to deploy the following functions in "dev" to the following regions:  
Serverless: us-east-1 ------------------------  
Serverless:   gremlin/search: Expected params.Role to be a string  

Regards,

Dean

**Comment by martinlindenberg** [comment]
Hi Dean,

when a lambda function is uploaded to aws, a role to execute this function will be attached to it.

Serverless creates this automatically for you: 
[projectname]-[stagename]-r-IamRoleLambda-[hash]

(in my case "testvpc-dev-r-IamRoleLambda-FV1NJAKY2ABY")

You can find this role in the configuration tab of your function in the aws console.

To add the permissions i did the following:
Go to IAM > Roles and select this specific role.
In the tab Permissions you can find on top Managed Policies and on bottom Inline Policies.

I created a new Inline Policy with the following contents:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by kapsoft** [comment]
Hi again,

That was great help getting it to deploy. Thanks.

But with everything deployed correctly I'm now getting a 403 forbidden error or testing it from API console:

Execution log for request test-request
Sat Feb 20 17:11:07 UTC 2016 : Starting execution for request: test-invoke-request
Sat Feb 20 17:11:07 UTC 2016 : API Key: test-invoke-api-key
Sat Feb 20 17:11:07 UTC 2016 : Method request path: {}
Sat Feb 20 17:11:07 UTC 2016 : Method request query string: {}
Sat Feb 20 17:11:07 UTC 2016 : Method request headers: {}
Sat Feb 20 17:11:07 UTC 2016 : Method request body before transformations: null
Sat Feb 20 17:11:07 UTC 2016 : Endpoint request URI: https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:us-east-1:811622120671:function:isdb-serverless-gremlin-search:will/invocations
Sat Feb 20 17:11:07 UTC 2016 : Endpoint request headers: {x-amzn-lambda-integration-tag=test-request, Authorization=**************************************************************************************************************************************************************************************************************************************************************************************c62cdf, X-Amz-Date=20160220T171107Z, x-amzn-apigateway-api-id=1ohl7d7ngj, X-Amz-Source-Arn=arn:aws:execute-api:us-east-1:811622120671:1ohl7d7ngj/null/GET/search, Accept=application/json, User-Agent=AmazonAPIGateway_1ohl7d7ngj, Host=lambda.us-east-1.amazonaws.com}
Sat Feb 20 17:11:07 UTC 2016 : Endpoint request body after transformations: null
Sat Feb 20 17:11:07 UTC 2016 : Execution failed due to configuration error: Invalid permissions on Lambda function
Sat Feb 20 17:11:07 UTC 2016 : Method completed with status: 500

I added the vpclambdaexecute policy manually from console to this role. Do u know anything obvious I might be missing? 

Thanks again....

Dean

**Comment by kapsoft** [comment]
Update: I think I got past this problem and on to the next one. LOL.

Thx for your help...

Dean
